import { useEffect, useMemo, useState } from 'react';
import { Search, SlidersHorizontal, ShoppingBag, ArrowUpRight, X } from 'lucide-react';
import { ProductDetail } from './product';

type Product = { id: string; name: string; slug: string; description?: string; price: number; stock: number; status: string };
const API = import.meta.env.VITE_API_URL ?? 'http://localhost:8080';

type StockFilter = 'all' | 'available' | 'out';

export function Catalog() {
  const [products, setProducts] = useState<Product[]>([]); const [query,setQuery]=useState(''); const [selected,setSelected]=useState<string|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [filterOpen,setFilterOpen]=useState(false); const [stockFilter,setStockFilter]=useState<StockFilter>('all');
  useEffect(()=>{fetch(`${API}/api/v1/products?limit=48`).then(r=>{if(!r.ok)throw new Error('Unable to load products');return r.json()}).then(setProducts).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
  const filtered=useMemo(()=>products.filter(p=>`${p.name} ${p.description??''}`.toLowerCase().includes(query.toLowerCase())).filter(p=>stockFilter==='all'||(stockFilter==='available'?p.stock>0:p.stock===0)),[products,query,stockFilter]);
  if(selected)return <ProductDetail id={selected} onBack={()=>setSelected(null)}/>;
  return <section className="catalog" id="shop"><header className="catalog-head"><div><span className="eyebrow">THE COLLECTION</span><h2>Explore products.</h2></div><div className="catalog-tools"><label><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products" /></label><button className={`filter ${filterOpen?'active':''}`} onClick={()=>setFilterOpen(v=>!v)}><SlidersHorizontal size={17}/> Filter</button>{filterOpen&&<div className="filter-menu"><div className="filter-title">Availability <button aria-label="Close filters" onClick={()=>setFilterOpen(false)}><X size={15}/></button></div>{(['all','available','out'] as StockFilter[]).map(value=><button key={value} className={stockFilter===value?'selected':''} onClick={()=>{setStockFilter(value);setFilterOpen(false)}}>{value==='all'?'All products':value==='available'?'In stock':'Out of stock'}</button>)}</div>}</div></header>{loading&&<div className="catalog-state">Loading the collection…</div>}{error&&<div className="catalog-state">{error}</div>}{!loading&&!error&&<div className="grid">{filtered.map(product=><article className="card" key={product.id} onClick={()=>setSelected(product.id)}><div className="card-visual"><span>{product.status}</span><button aria-label={`View ${product.name}`} onClick={e=>{e.stopPropagation();setSelected(product.id)}}><ShoppingBag size={18}/></button></div><div className="card-meta"><div><h3>{product.name}</h3><p>{product.description||'Discover this Olympus product.'}</p></div><strong>৳{Number(product.price).toLocaleString('en-BD')}</strong></div><div className="stock">{product.stock>0?`${product.stock} available`:'Out of stock'} <ArrowUpRight size={14}/></div></article>)}</div>}{!loading&&!error&&filtered.length===0&&<div className="catalog-state">No products match your filters.</div>}</section>;
}
