import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, CheckCircle2, Clock3, Package, Truck } from 'lucide-react';
import './orders.css';
const API=import.meta.env.VITE_API_URL??'http://localhost:8080';
type Order={id:string;status:string;currency:string;subtotal:number;shipping_amount:number;tax_amount:number;total_amount:number;created_at:string};
const stages=['PENDING','PAID','PROCESSING','SHIPPED','DELIVERED'];
function stage(status:string){const i=stages.indexOf(status);return i<0?0:i}
export function Orders({onBack}:{onBack:()=>void}){const token=localStorage.getItem('olympus_token');const [orders,setOrders]=useState<Order[]>([]);const [selected,setSelected]=useState<Order|null>(null);const [error,setError]=useState('');useEffect(()=>{if(token)fetch(`${API}/api/v1/orders`,{headers:{Authorization:`Bearer ${token}`}}).then(r=>{if(!r.ok)throw new Error('Unable to load orders');return r.json()}).then(setOrders).catch(e=>setError(e.message))},[token]);if(!token)return <section className="orders-page"><button className="back" onClick={onBack}><ArrowLeft size={17}/> Continue shopping</button><div className="orders-empty"><Package/><h2>Sign in to view orders.</h2></div></section>;return <section className="orders-page"><button className="back" onClick={onBack}><ArrowLeft size={17}/> Continue shopping</button><div className="orders-heading"><span className="eyebrow">YOUR ACCOUNT</span><h1>My orders.</h1></div>{error&&<div className="orders-empty">{error}</div>}{!error&&!selected&&orders.length===0&&<div className="orders-empty"><Package size={32}/><h2>No orders yet.</h2><p>Your purchases will appear here.</p></div>}{!error&&!selected&&orders.map(o=><button className="order-row" key={o.id} onClick={()=>setSelected(o)}><div><span>ORDER {o.id.slice(0,8).toUpperCase()}</span><b>{new Date(o.created_at).toLocaleDateString('en-GB')}</b></div><div><strong>৳{Number(o.total_amount).toLocaleString('en-BD')}</strong><small>{o.status}</small></div><ArrowRight size={17}/></button>)}{selected&&<OrderTracking order={selected} onBack={()=>setSelected(null)}/>}</section>}
function OrderTracking({order,onBack}:{order:Order;onBack:()=>void}){const current=stage(order.status);return <div className="tracking"><button className="back" onClick={onBack}><ArrowLeft size={17}/> Back to orders</button><span className="eyebrow">ORDER {order.id.slice(0,8).toUpperCase()}</span><h2>Order tracking.</h2><div className="tracker">{stages.slice(1).map((s,i)=>{const done=current>=i+1;const Icon=i===1?CheckCircle2:i===2?Truck:i===3?Package:Clock3;return <div className={done?'track done':'track'} key={s}><div className="dot"><Icon size={17}/></div><span>{s}</span></div>})}</div><div className="tracking-total"><span>Total paid</span><b>৳{Number(order.total_amount).toLocaleString('en-BD')}</b></div><div className="tracking-meta"><span>Subtotal <b>৳{Number(order.subtotal).toLocaleString('en-BD')}</b></span><span>Shipping <b>৳{Number(order.shipping_amount).toLocaleString('en-BD')}</b></span><span>Tax <b>৳{Number(order.tax_amount).toLocaleString('en-BD')}</b></span></div></div>}
