import { useState } from 'react';
import { ArrowLeft, ArrowRight, CheckCircle2, CreditCard, Smartphone } from 'lucide-react';
import './payment.css';

const API=import.meta.env.VITE_API_URL??'http://localhost:8080';
type Props={orderId:string;amount:number;onBack:()=>void;onDone:()=>void};
export function Payment({orderId,amount,onBack,onDone}:Props){const token=localStorage.getItem('olympus_token');const [provider,setProvider]=useState('STRIPE');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [paid,setPaid]=useState(false);
 async function pay(){if(!token)return;setBusy(true);setError('');try{const a=await fetch(`${API}/api/v1/orders/${orderId}/payments`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({provider})});if(!a.ok)throw new Error('Unable to start payment.');const p=await a.json();const b=await fetch(`${API}/api/v1/payments/${p.id}/verify`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({provider_reference:`OLY-${p.id.slice(0,8)}`,success:true})});if(!b.ok)throw new Error('Payment verification failed.');setPaid(true)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(paid)return <section className="payment-page"><div className="success"><CheckCircle2 size={58}/><span className="eyebrow">PAYMENT CONFIRMED</span><h1>Order secured.</h1><p>Your payment has been verified and your order is now confirmed.</p><button className="pay-btn" onClick={onDone}>View my orders <ArrowRight size={17}/></button></div></section>;
 return <section className="payment-page"><button className="back" onClick={onBack}><ArrowLeft size={17}/> Back to checkout</button><div className="payment-heading"><span className="eyebrow">PAYMENT</span><h1>Choose how to pay.</h1></div><div className="payment-grid"><div className="methods">{[['STRIPE','Card payment',CreditCard],['BKASH','bKash',Smartphone],['NAGAD','Nagad',Smartphone]].map(([id,label,Icon]:any)=><button className={`method ${provider===id?'selected':''}`} onClick={()=>setProvider(id)} key={id}><Icon size={21}/><span><b>{label}</b><small>{id==='STRIPE'?'Visa, Mastercard and more':'Mobile financial service'}</small></span><i/></button>)}</div><aside className="pay-summary"><span className="eyebrow">TOTAL</span><strong>৳{Number(amount).toLocaleString('en-BD')}</strong><button className="pay-btn" disabled={busy} onClick={pay}>{busy?'Verifying…':'Continue securely'} <ArrowRight size={17}/></button>{error&&<small>{error}</small>}</aside></div></section>}
